document_type: "customer"
version: "1.0"
description: "Customer contract for 32H (SEU) - Source to Silver to NetSuite mapping"
source_type: "api"
region: "seu"
entity_code: "32H"

# Source to Silver mapping
source_to_silver:
  - source_column: "Code"
    target_column: "customer_id"
    source_data_type: "string"
    target_data_type: "string"
    required: true
    description: "Customer unique identifier"
    validation_rules: ["not_null", "unique"]
    transformations: []
    notes: "Customer code from Entersoft API"
  
  - source_column: "Name"
    target_column: "company_name"
    source_data_type: "string"
    target_data_type: "string"
    required: false
    description: "Customer name"
    validation_rules: []
    transformations: []
    notes: "Customer name from API"
  
  - source_column: "EMailAddress"
    target_column: "email"
    source_data_type: "string"
    target_data_type: "string"
    required: false
    description: "Customer email address"
    validation_rules: []
    transformations: []
    notes: "Email from API"
  
  - source_column: "Phone"
    target_column: "phone"
    source_data_type: "string"
    target_data_type: "string"
    required: false
    description: "Customer phone number"
    validation_rules: []
    transformations: []
    notes: "Phone from API"
  
  - source_column: "TaxRegNumber"
    target_column: "tax_reg_number"
    source_data_type: "string"
    target_data_type: "string"
    required: false
    description: "Tax registration number"
    validation_rules: []
    transformations: []
    notes: "Tax registration from API"
  
  - source_column: "Country"
    target_column: "country"
    source_data_type: "string"
    target_data_type: "string"
    required: true
    description: "Country code"
    validation_rules: ["not_null", "length:2"]
    transformations: []
    notes: "Country from API"
  
  - source_column: "Inactive"
    target_column: "is_company"
    source_data_type: "boolean"
    target_data_type: "boolean"
    required: true
    description: "Is customer a company"
    validation_rules: ["not_null"]
    transformations: ["invert_boolean"]
    notes: "Inactive flag (inverted for is_company logic)"
  
  - source_column: "32H"
    target_column: "entity"
    source_data_type: "string"
    target_data_type: "string"
    required: true
    description: "Entity code"
    validation_rules: ["not_null"]
    transformations: ["literal('32H')"]
    notes: "Fixed value for 32H entity"

# Silver to NetSuite mapping
silver_to_netsuite:
  - silver_column: "customer_id"
    netsuite_field: "entityId"
    netsuite_type: "string"
    required: true
    soap_mapping: "Customer.entityId"
    description: "Customer ID visible in NetSuite"
  
  - silver_column: "company_name"
    netsuite_field: "companyName"
    netsuite_type: "string"
    required: false
    soap_mapping: "Customer.companyName"
    description: "Company name for business customers"
  
  - silver_column: "email"
    netsuite_field: "email"
    netsuite_type: "string"
    required: false
    soap_mapping: "Customer.email"
    description: "Customer email address"
  
  - silver_column: "phone"
    netsuite_field: "phone"
    netsuite_type: "string"
    required: false
    soap_mapping: "Customer.phone"
    description: "Customer phone number"
  
  - silver_column: "tax_reg_number"
    netsuite_field: "vatRegNumber"
    netsuite_type: "string"
    required: false
    soap_mapping: "Customer.vatRegNumber"
    description: "VAT registration number"
  
  - silver_column: "entity"
    netsuite_field: "subsidiary"
    netsuite_type: "RecordRef"
    required: true
    soap_mapping: "Customer.subsidiary"
    nested: true
    lookup: "subsidiary_map"
    description: "Subsidiary reference based on entity"

# NetSuite SOAP Configuration
netsuite_config:
  object_type: "Customer"
  operation: "upsertList"
  batch_size: 100
  retry_attempts: 3
  timeout_seconds: 30
  
  # Required fields for NetSuite Customer
  required_fields:
    - "entityId"
    - "subsidiary"
  
  # Optional fields
  optional_fields:
    - "companyName"
    - "email"
    - "phone"
    - "vatRegNumber"

# Lookup Tables
lookups:
  subsidiary_map:
    "32H": 37  # SEU subsidiary ID (to be confirmed)

